config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  get 'users/show'
  get 'users/edit'
  post 'users/update'
  delete 'users/destroy'  
  resources :users, only: [:create]
  resources :sessions, only: [:create]

  resources :articles do 
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }

  self.per_page = 3

  def article_commentable_type?
    true
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy

  validates :body, presence: true,
                   length: { minimum: 5 }

  self.per_page = 5

  def article_commentable_type?
    false
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :login, presence: true, uniqueness: true
  validates :password, length: { minimum: 3}, :if => :password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authorize

  helper_method :current_user
  
  protected
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    else
      @current_user = nil
    end
  end

  def authorize
    redirect_to login_path(:before_login_path => request.path), alert: 'You must be logged in to access this page.' if current_user.nil?
  end

  def drop_session
    session[:user_id] = nil
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, except: [:index, :new, :create, :show]

  skip_before_action :authorize, only: [:show]

  def index
    @articles = current_user.articles.includes(:user)

    if params.has_key? :search
      @search = params[:search]
      @articles = @articles.where("title like ?", "%#{@search}%")
    end

    @articles = @articles.order(created_at: :desc).page(params[:page])   
  end

  def show
    @article = Article.find(params[:id])
    @comment_page = params[:page]
    @comments = @article.comments.order(created_at: :desc).paginate(:page => @comment_page)
  end    

  def new
    @article = current_user.articles.build
  end

  def edit
  end

  def create
    @article = current_user.articles.create(article_params)

    if @article.valid?
      flash[:success] = "Article was successfully created!"
      redirect_to @article
    else  
      flash[:alert] = "Acticle wasn't created!"
      render 'new'      
    end
  end

  def update
    if @article.update(article_params)
      flash[:success] = "Article was successfully updated!"
      redirect_to @article
    else
      flash[:alert] = "Acticle wasn't updated!"
      render 'edit'
    end
  end

  def destroy
    if @article.destroy
      flash[:success] = "Article was successfully deleted!"
    else
      flash[:error] = "Something went wrong, the acticle wasn't deleted"
    end
    redirect_to articles_path
  end

  private
  def set_article
    @article = current_user.articles.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :text, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_article
  before_action :find_commentable
  before_action :find_reply_type, only: [:new, :create]

  def new
    @comment = @commentable.comments.build(user_id: current_user.id) 

    my_love = "something"
    respond_to do |format|
      format.js
    end
  end

  def create
    @comment = @commentable.comments.create(comment_params)

    if @comment.valid?
      flash.now[:success] = "Your comment was successfully created!"
      respond_to do |format|
      # format.html { redirect_to article_path(@article) }
        format.js
      end  
    else
      flash.now[:alert] = "Comment wasn't created!"
      render 'new'      
    end  
  end

  def destroy
    @comment = @commentable.comments.find(params[:id])
    if @commentable.article_commentable_type?
      @comment_page = params[:page]
      @comments = @article.comments.order(created_at: :desc).paginate(:page => @comment_page)
    end

    if @comment.destroy
      flash[:success] = "Comment was successfully deleted!"
    else
      flash[:error] = "Something went wrong, the comment wasn't deleted"
    end
    respond_to do |format|
      format.js
      # format.html { redirect_to article_path(@article) }
    end
  end


  private
  def find_reply_type
    @reply_type = params[:comment_id] ? 'comment-reply' : 'article-reply'
  end

  def set_article
    @article = Article.find(params[:article_id])
  end

  def find_commentable
      @commentable = Article.find_by_id(params[:article_id]) if params[:article_id]
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
  end

  def comment_params
    params.require(:comment).permit(:body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorize

  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id

      UserMailer.with(user: user).sample_email.deliver_now
      
      redirect_to params[:return_url], notice: "Logged in!"
    else
      flash[:error] = "Email or password is invalid!"
      render "new"
    end
  end

  def destroy
    drop_session
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorize, only: [:create, :new]
  
  def show 
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Sign up!"
      redirect_to login_path
    else  
      flash[:error] = "Invalid data found when processing input!"
      render 'new'      
    end
  end

  def update
    @user = current_user
    params_to_update = user_params
    params_to_update.delete(:password) if params_to_update[:password].blank?

    if @user.update_attributes(params_to_update)
      flash[:success] = "Your account was successfully updated!"
      redirect_to users_show_path
    else
      flash[:alert] = "Your account wasn't updated!"
      render 'edit'
    end
  end

  def destroy
    @user = current_user
    if @user.destroy
      drop_session
      flash[:success] = "User was successfully deleted!"
      redirect_to login_path
    else
      flash[:error] = "Something went wrong, the user wasn't deleted!"
      redirect_to users_show_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :login, :email, :password, :password_confirmation, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :authorize

  def index
    if params.has_key? :search
      @search = params[:search]
      @articles = Article.where("title like ?", "%#{@search}%")
    else
      @articles = Article.all.order('created_at DESC').page(params[:page])
    end
  end

end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_class(level)
    case level
      when 'notice'
        "alert alert-info"
      when 'success'
        "alert alert-success"
      when 'error' 
        "alert alert-danger"
      when 'alert' 
        "alert alert-warning"
    end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/paginate_helper.rb
module PaginateHelper

  def custom_paginate_renderer
    Pagination::CustomPaginateRenderer.new
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article, local: true do |form| %>
  <%= render 'layouts/errors', model: @article, model_str: 'article' %>

  <div class="form-group">
    <%= form.label :image %><br>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :text %><br>
    <%= form.text_area :text, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-info" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="container h-100">
  <div class="col-md-7 mx-auto">
    <div class="border border-info rounded p-5">

      <h1>Edit Article</h1>
      <%= render 'form' %>

    </div>
  </div>
</div>

<%= link_to 'Back', articles_path, class: "btn btn-secondary btn-sm" %>

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<p>
    <%= link_to "New article", new_article_path, class: "btn btn-outline-primary"%> 
</p>

<%= render 'layouts/search_bar', our_path: articles_path %>

<p>
  <% flash.each do |key, value| %>
    <div> <%= key %>: <%= value %></div>
  <% end %>
</p>

<table class="table table-striped table-light table-bordered">
<thead class="thead-light">
  <tr>
    <th scope="col">Time</th>
    <th scope="col">Author</th>
    <th scope="col">Title</th>
    <th scope="col">Text</th>
    <th scope="col"></th>
  </tr>
  </thead>
 
  <div class="p-3"><%= will_paginate @articles, renderer: custom_paginate_renderer %></div>

  <% @articles.each do |article| %>
    <tr>
      <td scope="row" data-created="<%= article.created_at %>"></td>
      <td scope="row"><%= article.user.login %></td>
      <td scope="row"><%= article.title %></td>
      <td scope="row"><%= article.text %></td>
      <td scope="row">
        <%= link_to 'Show', article_path(article), class: "btn btn-info btn-sm" %>
        <%= link_to 'Edit', edit_article_path(article), class: "btn btn-info btn-sm" %>
        <%= link_to 'Destroy', article_path(article), class: "btn btn-info btn-sm",
                                  method: :delete,
                                  data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table>

<%= page_entries_info @articles %>
<p>
    <%= link_to "Main page", controller: 'welcome'%>
</p>

app/views/articles/new.html.erb
<div class="container h-100">
  <div class="col-md-7 mx-auto">
    <div class="border border-info rounded p-5">
    
      <h1>New Article</h1>
      <%= render 'form' %>
 
    </div>
  </div>
</div>

<%= link_to "Back", articles_path, class: "btn btn-secondary btn-sm"%>

app/views/articles/show.html.erb
<div class="article">
<div class="card">

  <div class="card-header">
    <p>
      <%= image_tag @article.image unless @article.image.nil? %>
    </p>
    <div class="row">
      <div class="col-md-5">
        <% unless @article.user.avatar.blank? %>        
          <%= image_tag @article.user.avatar.variant(resize_to_limit: [100, 100]), class: "mx-auto rounded-circle img-fluid"  %>
        <% end %>
      </div>
      <h3 class="col-md-7">
        <strong><%= @article.title %></strong>
      </h3> 
    </div>

    <div class="comment-content col-md-11 col-sm-10">
      <strong>Author:</strong>
      <h6 class="small comment-meta"><%= @article.user.login %></h6>
    </div>
  </div>

  <div class="card-body">
    <p class="card-text">
      <%= @article.text %>
    </p>
    
    <p>
      <% unless current_user.nil? %>
        <%= link_to "Leave a comment on the article", new_comment_path(:article_id => @article.id), 
                    remote: true, class: "btn btn-primary btn-sm article-link-reply" %>
      <% else %>
        <div>
          <%= link_to "Log In", login_path(:before_login_path => request.path) %>
          to leave a comment.
        </div> <br>
      <% end %>
    </p>
  </div>
 
</div>

<div class="article-comment w-25"></div>

<div class="container py-2">
    <div class="row">
        <div class="comments col-md-9">
            <h3 class="mb-4 font-weight-light">Comments</h3>

            <div id="comments-reload">
              <div class="p-3"><%= will_paginate @comments, renderer: custom_paginate_renderer %></div>
                <div id="comments">
                  <%= render @comments %>
                </div>
            </div>
            
        </div>
    </div>
</div>

<%= render 'layouts/time_localizer' %>
<p>
  <%= link_to 'Back', welcome_index_path, class: "btn btn-secondary btn-sm" %>
</p>

</div>

app/views/comments/_comment.html.erb
<div class="ml-5 pl-2 comment-block">
  <div class="comment mb-2 row">

    <!-- Author's avatar picture  --> 
    <div class="comment-avatar col-md-1 col-sm-2 text-center pr-1">
      <% unless comment.user.avatar.blank? %>
      <%= image_tag comment.user.avatar.variant(resize_to_limit: [100, 100]), class: "mx-auto rounded-circle img-fluid" %>
    <% end %>
    </div>

    <!-- Author's login and time --> 
    <div class="comment-content col-md-11 col-sm-10">
      <h6 class="small comment-meta">
        <%= comment.user.login %>
        ____ <em data-created="<%= comment.created_at %>"></em>
        <%= render 'layouts/time_localizer' %>
      </h6>

      <!-- Author's comment body --> 
      <div class="comment-body">
        <%= comment.body %>
      </div>
      
      <!-- Add reply button --> 
      <% unless(current_user.nil?) %>
        <%= link_to "Add reply", new_comment_path(:comment_id => comment.id, :article_id => @article.id), 
            remote: true, class: "text-right small reply" %>
      <% end %>

      <!-- Delete button --> 
      <% if comment.user == current_user %>

        <% if comment.commentable.article_commentable_type? %>
          <%= link_to 'Destroy Comment', [comment.commentable, comment, {:page => @comment_page}],
                      method: :delete,
                      data: { confirm: 'Are you sure?', remote: true },  
                      class: "text-right small delete"  %>
        <% else %>
          <%= link_to 'Destroy Comment', [comment.commentable, comment, {:article_id => @article.id} ],
                      method: :delete,
                      data: { confirm: 'Are you sure?', remote: true }, 
                      class: "text-right small delete"  %>
        <% end %>

      <% end %>

    </div>

    <div class="nested-comment-reply"></div>
  </div>
  
  <!-- Recursively invoke nested comments --> 
  <div class="nested-comments">
    <% unless comment.comments.blank? %>
      <%= render comment.comments.order(created_at: :desc) %>
    <% end %>
  </div>

</div>

app/views/comments/_form.html.erb
<h2>Add a comment:</h2>

<%= form_with(model: [ @article, @article.comments.build(user_id: @article.user_id) ],
local: true) do |form| %>
  <%= form.hidden_field :user_id %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_new.html.erb
<div class="border border-info rounded p-3 m-2 ml-5">

  <h5>Add a comment:</h5>
  <%= form_with(model: [@commentable, @comment], class: "#{@reply_type}") do |form| %>

    <%= render 'layouts/errors', model: @comment , model_str: 'comment' %>
    
    <%= hidden_field_tag "article_id", @article.id %>
    <%= form.hidden_field :user_id %>

    <div class="form-group">
      <%= form.text_area :body, class: "form-control", placeholder: "Write something..." %>
    </div>

    <div class="form-group">
      <%= form.submit 'Add the comment', class: "btn btn-info btn-sm"%>
    </div>
  <% end %>
</div>

app/views/comments/create.js.erb
<%= render partial: 'layouts/show_flash', formats: [:js] %>

$(".comment-reply")
  .on("ajax:success", function() {

    showFlashes();

    commentEl = $(this).closest(".comment");
    
    commentEl.parent()
             .children(".nested-comments")
             .prepend("<%= j render @comment %>");

    commentEl.find(".reply").show();

    $(this).closest(".nested-comment-reply")
           .empty();
  });


$(".article-reply")
  .on("ajax:success", function() {

    showFlashes();

    if ($("#comments").children(".comment-block").length === 5) {
      $("#comments").children(".comment-block")
                    .last().remove();
    }

    commentEl = $(this).closest(".article");

    commentEl.find(".article-link-reply").show();

    commentEl.find(".article-comment").empty();

    commentEl.find("#comments")
             .prepend("<%= j render @comment %>");  
  });

app/views/comments/destroy.js.erb
<% if @commentable.article_commentable_type? %>
  $(".delete").on("ajax:success", function() {
    $("#comments-reload")
      .html(`<div class="p-3"><%= will_paginate @comments, renderer: custom_paginate_renderer %></div>
              <div id="comments">
                <%= render @comments %>
              </div>`);
  });
<% else %>
  $(".delete").on("ajax:success", function() {
      $(this).closest(".comment-block").remove();
    });
<% end %>

app/views/comments/new.js.erb
<%= render partial: 'layouts/show_flash', formats: [:js]%>

$(".reply, .comment-reply")
  .on("ajax:success", function() {

    showFlashes();
    
    if ($(this).hasClass('.comment-reply')) {
      $(this).remove();
    } else {
      $(this).hide();
    }

    $(this).closest(".comment").find(".nested-comment-reply")
           .empty()
           .append("<%= j render 'new' %>");
  });


$(".article-link-reply, .article-reply")
  .on("ajax:success", function() {

    showFlashes();

    if ($(this).hasClass('.article-reply')) {
      $(this).remove();
    } else {
      $(this).hide();
    }

    $(this).closest(".article").find(".article-comment")
           .empty()
           .append("<%= j render 'new' %>");

  });

app/views/layouts/_errors.html.erb
<% if model.errors.any? %>
  <div class="alert alert-info" role="alert">
    <div id="error_explanation">
      <h4 class="alert-heading">
        <%= pluralize(model.errors.count, "error") %> prohibited
        this <%= model_str %> from being saved:
      </h4>
      <ul>
        <% model.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %>">
        <%= value %>
  </div>
<% end %>

app/views/layouts/_search_bar.html.erb
<form class="form-inline">
  <%= form_with(url: our_path, method: "get", local: true) do |form| %>
    <div class="form-group p-3" > 
      <%= form.text_field :search, :value => @search, placeholder: "Search", class: "form-control"%>
    </div>
    <button class="btn btn-info" type="search">Search</button>
   
  <% end %>
</form>

app/views/layouts/_show_flash.js.erb
function showFlashes() {
  $(".flashes").empty()
           .append("<%= j render 'layouts/flash' %>");
}

app/views/layouts/_time_localizer.html.erb
<script>
  $("td[data-created], em[data-created]").each(function() {
    $(this).html(new Date($(this).attr("data-created")).toLocaleString("ru"));
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="body">

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-brand">
      <%= link_to 'Blog', controller: 'welcome' %> 
      </div> | 

      <% if current_user %>
        <div class="nav-link disabled">
          Logged in as <span id="user-name"><%= current_user.login %> </span>
        </div> | 
        <div class="nav-link">
          <%= link_to 'My Blog', controller: 'articles'%>
        </div> | 
        <div class="nav-link">
          <%= link_to 'Manage Profile', users_show_path %>
        </div> | 
        <div class="nav-link"> 
          <%= link_to 'Log Out', logout_path %>
        </div>

      <% else %>
        <div class="nav-link">
          <%= link_to 'Sign Up', signup_path %>
        </div> | 
        <div class="nav-link">
          <%= link_to 'Log In', login_path %>
        </div>
      <% end %>
    </nav>

    <div id="margins">
      <div class="flashes"><%= render "layouts/flash" %></div>

      <%= yield %>
    </div>


    <%= render 'layouts/time_localizer' %>
    
  </body>
</html>

app/views/users/edit.html.erb
<div class="container h-100">
  <div class="col-md-7 mx-auto">
    <div class="border border-secondary rounded p-5">

      <h1>Editing User</h1>
      <%= form_with(model: current_user, url: users_update_path, method: 'post', local: true) do |form| %>
        <%= render 'layouts/errors', model: current_user, model_str: 'user' %>

        <div class="form-group">
          <%= form.label :avatar %>
          <%= form.file_field :avatar  %>
        </div>

        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :login %>
          <%= form.text_field :login, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.submit 'Save', class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="container h-100">
  <div class="col-md-7 mx-auto">
    <div class="border border-primary rounded p-5">

      <h1>Registration</h1>
      <%= form_with(model: @user, url: users_path, local: true) do |form| %>
        <%= render 'layouts/errors', model: @user, model_str: 'user'%>

        <div class="form-group">
          <%= form.label :avatar %>
          <%= form.file_field :avatar%>
        </div>
        
        <div class="form-group">
          <%= form.label :first_name %>
          <%= form.text_field :first_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :last_name %>
          <%= form.text_field :last_name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :login %>
          <%= form.text_field :login, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= form.text_field :email , class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :password %>
          <%= form.password_field :password, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :password_confirmation %>
          <%= form.password_field :password_confirmation, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.submit 'Sign Up', class: "btn btn-primary"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container h-100">
  <div class="col-md-5 mx-auto">
    <div class="border border-secondary rounded p-5">
      <h1>My account</h1>

      <% unless current_user.avatar.blank? %>
        <%= image_tag current_user.avatar.variant(resize_to_limit: [330, 330]) %>
      <% end %>

      <p>
        <strong>Name:</strong>
        <%= current_user.first_name %> <%= current_user.last_name %>
      </p>

      <p>
        <strong>Login:</strong>
        <%= current_user.login %>
      </p>

      <p>
        <strong>Email:</strong>
        <%= current_user.email %>
      </p>

      <%= link_to 'Edit', users_edit_path %> | 
      <%= link_to 'Destroy', users_destroy_path,
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<h1>Listing Articles</h1>

<%= render 'layouts/search_bar', our_path: welcome_index_path %>

<table class="table table-striped table-light table-bordered">
  <thead class="thead-light">
  <tr>
    <th scope="col">Time</th>
    <th scope="col">Author</th>
    <th scope="col">Title</th>
    <th scope="col">Text</th>
    <th scope="col"></th>
  </tr>
  </thead>

  <div class="p-3"><%= will_paginate @articles, renderer: custom_paginate_renderer %></div>

  <% @articles.each do |article| %>
    <tr>
      <td scope="row" data-created="<%= article.created_at %>"></td>
      <td scope="row"><%= article.user.login %></td>
      <td scope="row"><%= article.title %></td>
      <td scope="row"><%= article.text %></td>
      <td scope="row"><%= link_to 'Show', article_path(article), class: "btn btn-info btn-sm" %></td>
    </tr>
  <% end %>
</table>

 <%= page_entries_info @articles %>